apiVersion: apps/v1
kind: Deployment
metadata:
  name: behold-ui
  namespace: behold
  labels:
    app: behold-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: behold-ui
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: behold-ui
    spec:
      containers:
        - name: behold-ui
          image: registry.pettitservers.com:5000/behold-ui/behold-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
      imagePullSecrets:
        - name: registry-secret
