apiVersion: v1
kind: Service
metadata:
  name: behold-api
  namespace: behold
spec:
  selector:
    app: behold-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4040
      name: http
