apiVersion: apps/v1
kind: Deployment
metadata:
  name: behold-api-releases
  namespace: behold
  labels:
    app: behold-api-releases
spec:
  replicas: 1
  selector:
    matchLabels:
      app: behold-api-releases
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: behold-api-releases
    spec:
      containers:
        - name: behold-api-releases
          image: registry.pettitservers.com:5000/behold-api/behold-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4040
              name: http
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PORT
              value: "4040"
          command: ["bin/behold_api"]
          args: [
            "start"
          ]
      imagePullSecrets:
        - name: registry-secret
