apiVersion: v1
kind: Service
metadata:
  name: myplanespotter
  namespace: myplanespotter
spec:
  selector:
    app: myplanespotter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4040
      name: http
