apiVersion: v1
kind: Service
metadata:
  name: zeus-server
  namespace: zeus
spec:
  selector:
    app: zeus-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
      name: http
