apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-behold-ui
  namespace: behold
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: behold-ui.pettit.home
    http:
      paths:
      - path: /
        backend:
          serviceName: behold-ui
          servicePort: 80