apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-myplanespotter
  namespace: myplanespotter
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: myplanespotter.pettit.home
    http:
      paths:
      - path: /
        backend:
          serviceName: myplanespotter
          servicePort: 80